import React, { createContext, useContext, useEffect, useState } from 'react';
import { 
  signInWithCredential, 
  User, 
  onAuthStateChanged, 
  signInWithPopup, 
  signInWithRedirect,
  getRedirectResult,
  GoogleAuthProvider, 
  signOut,
  setPersistence,
  browserLocalPersistence
} from 'firebase/auth';
import { 
  doc, 
  getDoc, 
  setDoc, 
  updateDoc, 
  onSnapshot,
  collection,
  query,
  where,
  addDoc
} from 'firebase/firestore';
import { auth, db } from '../firebase';
import { SubscriptionTier } from '../types';
import { handleFirestoreError, OperationType } from '../utils/firestoreErrors';
import { GoogleAuth } from '@codetrix-studio/capacitor-google-auth';

interface UserData {
  uid: string;
  email: string;
  subscriptionTier: SubscriptionTier;
  trialEndTime?: number;
  createdAt: number;
  updatedAt: number;
}

interface AuthContextType {
  user: User | null;
  userData: UserData | null;
  loading: boolean;
  isAuthModalOpen: boolean;
  setAuthModalOpen: (open: boolean) => void;
  login: () => Promise<void>;
  loginWithGoogle: () => Promise<void>;
  logout: () => Promise<void>;
  updateSubscription: (tier: SubscriptionTier, trialDurationMs?: number) => Promise<void>;
  createStripeCheckout: (priceId: string, mode: 'subscription' | 'payment') => Promise<void>;
}

const AuthContext = createContext<AuthContextType>({
  user: null,
  userData: null,
  isAuthModalOpen: false,
  setAuthModalOpen: () => {},
  loading: true,
  login: async () => {},
  loginWithGoogle: async () => {},
  logout: async () => {},
  updateSubscription: async () => {},
  createStripeCheckout: async () => {},
});

export const useAuth = () => useContext(AuthContext);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [user, setUser] = useState<User | null>(null);
  const [userData, setUserData] = useState<UserData | null>(null);
  const [stripeTier, setStripeTier] = useState<SubscriptionTier>('free');
  const [loading, setLoading] = useState(true);
  const [isAuthModalOpen, setAuthModalOpen] = useState(false);

  // --- STRIPE EXTENSION INTEGRATION ---
  const createStripeCheckout = async (priceId: string, mode: 'subscription' | 'payment') => {
    if (!user) return;
    try {
      setLoading(true);
      const docRef = await addDoc(
        collection(db, "users", user.uid, "checkout_sessions"),
        {
          price: priceId,
          success_url: window.location.origin,
          cancel_url: window.location.origin,
          mode: mode,
        }
      );

      // Listen for the URL generated by the Stripe extension
      const unsubscribe = onSnapshot(docRef, (snap) => {
        const data = snap.data();
        if (data?.error) {
          console.error("Stripe Checkout Error: ", data.error.message);
          alert(`Hubo un error con el pago: ${data.error.message}`);
          setLoading(false);
          unsubscribe();
        }
        if (data?.url) {
          window.location.assign(data.url);
          unsubscribe();
        }
      });
    } catch (error) {
      console.error("Error creating checkout session:", error);
      setLoading(false);
    }
  };

  useEffect(() => {
    // Ensure persistence is set to LOCAL
    setPersistence(auth, browserLocalPersistence).catch(err => console.error("Persistence error:", err));

    // Handle Redirect Result for Capacitor/Electron
    getRedirectResult(auth)
      .then((result) => {
        if (result?.user) {
          console.log("Redirect login success:", result.user.email);
          setAuthModalOpen(false);
        }
      })
      .catch((err) => {
        if (err.code !== 'auth/no-auth-event') {
          console.warn("Redirect result error handled:", err.code);
        }
      });

    let unsubscribeDoc: (() => void) | undefined;
    let unsubscribeSubs: (() => void) | undefined;
    let unsubscribePayments: (() => void) | undefined;

    const unsubscribeAuth = onAuthStateChanged(auth, async (currentUser) => {
      setUser(currentUser);
      
      if (!currentUser) {
        setUserData(null);
        setStripeTier('free');
        setLoading(false);
        if (unsubscribeDoc) { unsubscribeDoc(); unsubscribeDoc = undefined; }
        if (unsubscribeSubs) { unsubscribeSubs(); unsubscribeSubs = undefined; }
        if (unsubscribePayments) { unsubscribePayments(); unsubscribePayments = undefined; }
        return;
      }

      // 1. Listen to Local Database Record
      const userRef = doc(db, 'users', currentUser.uid);
      
      unsubscribeDoc = onSnapshot(userRef, async (docSnap) => {
        const isMaestro = currentUser.email === 'alexbordongarrigos@gmail.com';
        
        if (docSnap.exists()) {
          const data = docSnap.data() as UserData;
          // Force upgrade if they are maestro but not yet on lifetime
          if (isMaestro && data.subscriptionTier !== 'lifetime') {
            try {
              await updateDoc(userRef, { subscriptionTier: 'lifetime', updatedAt: Date.now() });
              data.subscriptionTier = 'lifetime';
            } catch (error) {
              handleFirestoreError(error, OperationType.UPDATE, `users/${currentUser.uid}`);
            }
          }
          setUserData(data);
        } else {
          // Create new user profile
          const newUserData: UserData = {
            uid: currentUser.uid,
            email: currentUser.email || '',
            subscriptionTier: isMaestro ? 'lifetime' : 'free',
            createdAt: Date.now(),
            updatedAt: Date.now(),
          };
          try {
            await setDoc(userRef, newUserData);
            setUserData(newUserData);
          } catch (error) {
            handleFirestoreError(error, OperationType.CREATE, `users/${currentUser.uid}`);
          }
        }
        setLoading(false);
      }, (error) => {
        handleFirestoreError(error, OperationType.GET, `users/${currentUser.uid}`);
        setLoading(false);
      });

      // 2. Listen to Stripe Extension 'subscriptions' (Annual Plan)
      const subsQuery = query(collection(db, 'users', currentUser.uid, 'subscriptions'), where('status', 'in', ['trialing', 'active']));
      unsubscribeSubs = onSnapshot(subsQuery, (snap) => {
        if (!snap.empty) {
          setStripeTier(prev => prev === 'lifetime' ? 'lifetime' : 'annual');
        } else {
          setStripeTier(prev => prev === 'annual' ? 'free' : prev);
        }
      }, (err) => console.log('Stripe Ext not set up yet (subs) or perms issue', err));

      // 3. Listen to Stripe Extension 'payments' (Lifetime Plan)
      const paysQuery = query(collection(db, 'users', currentUser.uid, 'payments'), where('status', '==', 'succeeded'));
      unsubscribePayments = onSnapshot(paysQuery, (snap) => {
        if (!snap.empty) {
          setStripeTier('lifetime');
        }
      }, (err) => console.log('Stripe Ext not set up yet (pays) or perms issue', err));
    });

    return () => {
      unsubscribeAuth();
      if (unsubscribeDoc) unsubscribeDoc();
      if (unsubscribeSubs) unsubscribeSubs();
      if (unsubscribePayments) unsubscribePayments();
    };
  }, []);

  const loginWithGoogle = async () => {
    const provider = new GoogleAuthProvider();
    provider.addScope('email');
    provider.addScope('profile');
    
    const isElectron = navigator.userAgent.toLowerCase().includes('electron');
    const isCapacitor = (window as any).Capacitor?.isNative;
    const isFileProtocol = window.location.protocol === 'file:';
    const isLocalServer = window.location.hostname === '127.0.0.1' || window.location.hostname === 'localhost';

    console.log("Login attempt in environment:", { isElectron, isCapacitor, isFileProtocol, isLocalServer });

    if (isCapacitor) {
      console.log("Native Capacitor environment: Attempting native GoogleAuth.signIn()...");
      try {
        const result = await GoogleAuth.signIn();
        if (result && result.authentication.idToken) {
           const credential = GoogleAuthProvider.credential(result.authentication.idToken);
           await signInWithCredential(auth, credential);
           console.log("Native Google login success:", result.email);
           setAuthModalOpen(false);
           return;
        }
      } catch (err: any) {
        console.error("Native GoogleAuth failed:", err);
        if (err.code === '12501' || err.message?.includes('12501')) return;
      }
    }

    // Default to Redirect for Mobile/Electron, Popup for Desktop Web
    const isMobile = /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
    
    if (isMobile || isElectron || isCapacitor) {
      console.log("Mobile/Native environment: Using signInWithRedirect...");
      try {
        await signInWithRedirect(auth, provider);
      } catch (err: any) {
        console.error("Redirect login failed:", err);
        alert("Error de autenticación: Verifique que 'audiomorphic.app' esté en los Dominios Autorizados de Firebase.");
      }
    } else {
      console.log("Desktop environment: Attempting signInWithPopup...");
      try {
        const result = await signInWithPopup(auth, provider);
        console.log("Popup login success:", result.user.email);
        setAuthModalOpen(false);
      } catch (error: any) {
        console.warn("Popup blocked or failed, retrying with redirect:", error.code);
        await signInWithRedirect(auth, provider);
      }
    }
  };

  // Alias for backward compatibility with new v1.0 components
  const login = loginWithGoogle;

  const logout = async () => {
    try {
      await signOut(auth);
    } catch (error) {
      console.error("Logout failed:", error);
    }
  };

  const updateSubscription = async (tier: SubscriptionTier, trialDurationMs?: number) => {
    if (!user) return;
    
    const userRef = doc(db, 'users', user.uid);
    const now = Date.now();
    const updates: Partial<UserData> = {
      subscriptionTier: tier,
      updatedAt: now,
    };

    if (tier === 'trial') {
      // Default: 1 hour for Viajero. Promo code passes 15 days.
      const duration = trialDurationMs || (1 * 60 * 60 * 1000); // 1 hour default
      updates.trialEndTime = now + duration;
    } else {
      updates.trialEndTime = undefined;
    }

    try {
      await updateDoc(userRef, updates);
    } catch (error) {
      handleFirestoreError(error, OperationType.UPDATE, `users/${user.uid}`);
    }
  };

  // Compute effective tier taking Stripe Extension Webhooks into account
  const computeEffectiveTier = (): SubscriptionTier => {
    if (!userData) return 'free';
    if (userData.subscriptionTier === 'lifetime' || stripeTier === 'lifetime') return 'lifetime';
    if (userData.subscriptionTier === 'annual' || stripeTier === 'annual') return 'annual';
    if (userData.subscriptionTier === 'trial' && userData.trialEndTime && Date.now() < userData.trialEndTime) return 'trial';
    return 'free';
  };

  const computedUserData = userData ? { ...userData, subscriptionTier: computeEffectiveTier() } : null;

  return (
    <AuthContext.Provider value={{ user, userData: computedUserData, loading, isAuthModalOpen, setAuthModalOpen, login, loginWithGoogle, logout, updateSubscription, createStripeCheckout }}>
      {children}
    </AuthContext.Provider>
  );
};
